baseURL: "https://ligon.github.io/"
#relativeURLs: true
#canonifyURLs: true
title: Ethan Ligon
theme: PaperMod
languageCode: en-us

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

params:
    description: "This website hosts material related to Ethan Ligon's research papers, course materials, data, curriculum vitae, and contact information."
    author: Ethan Ligon
    googleAnalyticsID: "G-SJQ9VEHFN1"
    math: true
    hideFooter: true
    MainSections: ["papers",]

    profileMode:
          enabled: true
          title: Ethan Ligon
          subtitle: "I am a Professor in the Department of Agricultural & Resource Economics at the University of California, Berkeley."
          imageUrl: "ligon.jpg"
          imageWidth: 320
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ligon@berkeley.edu
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: googlescholar
          url: https://scholar.google.com/citations?user=jRwNfxwAAAAJ
        - name: GitHub
          url: https://github.com/ligon
        - name: ORCID
          url: https://orcid.org/0000-0003-4928-0616

          # Other socialIcons relevant (`grep themes/PaperMod/layouts/partials/svg.html`)
          # signal pgpkey orcid strava orcid researchgate spotify wiki


    assets:
        favicon: "assets/favicon.ico"
        favicon16x16: "assets/favicon-16x16.png"
        favicon32x32: "assets/favicon-32x32.png"
        apple_touch_icon: "assets/apple-touch-icon.png"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ethan Ligon"
      icon: favicon.ico
      iconHeight: 18


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

