name: Deploy Hugo site

on:
  push:
    branches:
      - master  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Fetches and initializes submodules


    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 24.5

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y hugo
        # Additional dependencies if needed (e.g., fonts, themes)

    - name: Install ox-hugo
      run: |
        emacs --batch \
        --eval "(require 'package)" \
        --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
        --eval "(package-initialize)" \
        --eval "(unless (package-installed-p 'ox-hugo) (package-refresh-contents) (package-install 'ox-hugo))"

    - name: Export org to markdown
      run: |
        emacs --batch -l org -l ox-hugo --visit org/website.org --funcall org-hugo-export-to-md

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

