name: Deploy Hugo site

on:
  push:
    branches:
      - master  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Fetches and initializes submodules
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.148.2'
        extended: true
    - name: Build Site
      run: hugo


    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1

    - name: Install ox-hugo from GitHub
      run: |
        git clone https://github.com/kaushalmodi/ox-hugo.git ox-hugo
        emacs --batch -Q \
          --eval "(add-to-list 'load-path \"ox-hugo\")" \
          --eval "(require 'ox-hugo)"

    - name: Export org to markdown
      run: |
        echo "Current directory:"
        pwd
        echo "location of website.org:"
        find . -name PaperMod
        emacs --batch -Q \
          --eval "(add-to-list 'load-path \"ox-hugo\")" \
          --eval "(require 'org)" \
          --eval "(require 'ox-hugo)"
          --find-file "content-org/website.org" \
          --eval "(org-hugo-export-wim-to-md :all-subtrees)"

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public


# END
