name: Deploy Hugo site

on:
  push:
    branches:
      - master  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Fetches and initializes submodules
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.148.2'
        extended: true
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1

    - name: Install ox-hugo from MELPA; Export org to markdown
      run: |
        emacs --batch \
          --eval "(require 'package)" \
          --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
          --eval "(package-initialize)" \
          --eval "(unless (package-installed-p 'ox-hugo) (package-refresh-contents) (package-install 'ox-hugo))" \
          --eval "(require 'org)" \
          --eval "(require 'ox-hugo)" \
          --find-file "content-org/website.org" \
          --eval "(org-hugo-export-wim-to-md :all-subtrees)"

    - name: Build Hugo site
      run: |
        hugo --minify
        find . -name \*.css

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public


# END
